### ISSUE TITLE
Registration via Facebook is not working

### ISSUE THREAD

**Issue by DarkDeny** [dreikanter/bookmarkz#1] opened 2015-03-03 09:21 UTC
Facebook reply was:
Приложение не настроено: Разработчики настоящего приложения не настроили это приложение для входа на Facebook.

**Comment by dreikanter** [comment] 2015-03-03 09:46
That's weird. I can't reproduce it. Need to investigate.

**Comment by DarkDeny** [comment] 2015-03-03 09:54
On my windows 8 machine with Firefox for Developers browser - reproducible. I am using dev.mar.kz URL. Is this correct?

**Comment by dreikanter** [comment] 2015-03-03 09:55
It's correct.

**Comment by DarkDeny** [comment] 2015-03-03 10:12
Just checked - on macbook with Chrome behavior is the same. And I also
checked that I am logged in FB.

On Tue, Mar 3, 2015 at 12:55 PM, Alex Musayev <notifications@github.com>
wrote:

> It's correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreikanter/bookmarkz/issues/1#issuecomment-76916755>.
>



-- 
Regards,
 Dmitry D.

**Comment by dreikanter** [comment] 2015-03-09 11:40
The reason you can't register with Facebook account but I can is that the Facebook application account is in Development mode. I've discovered that to switch to Production mode the app needs to pass a review on FB. And in its turn to pass this review it is obligatory to have Privacy policy, and most likely Terms of service pages.

For now just use email registration on staging. I'm closing this issue and will add new action item for production environment setup.

![](https://monosnap.com/file/RhwZPGv0g4Le89lMHCIGZs5BBRoR41.png)

![](https://monosnap.com/file/MC2jTxmNACCmsT060eOgrS8dzIzDyX.png)

**Closed by dreikanter** 2015-03-09 11:40 UTC
